org: prshntb
app: findhalfloaves
# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: findhalfloaves

frameworkVersion: '3'

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-1
  stackName: halfloaves

# The `functions` block defines what code to deploy
functions:
  halfloaves:
    handler: halfloaves.handler
    events:
      - http:
        path: find
        method: post
        cors: true