org: prshntb
app: findhalfloaves
service: findhalfloaves
frameworkVersion: '3'
provider:
  name: aws
  runtime: nodejs14.x
  region: ap-south-1
  stackName: halfloaves
  timeout: 60
functions:
  halfloaves:
    handler: halfloaves.handler
    events:
      - http:
          path: findhalfloaves
          method: get
          cors: true
plugins:
  - serverless-esbuild
  - serverless-offline